### ISSUE TITLE
Release branch contains snapshot version 

### ISSUE THREAD

**Issue by spetrychenko** [borisskert/release-scripts#8]
When my release was completed. The release branch contains pom.xml with`SNAPSHOT` version

**Comment by borisskert** [comment]
Hi. Is your project public? May I have a look into it?

**Comment by DG0lden** [comment]
Hi Boris,

we have the same here: https://github.com/adorsys/xs2a/tree/release-1.16
Our hooks are:
https://github.com/adorsys/xs2a/blob/release-1.16/scripts/.release-scripts-hooks.sh

regards, Denys

**Comment by borisskert** [comment]
Hi. I have fixed it in this branch: https://github.com/borisskert/release-scripts/pull/14
Could you both verify it if your issue is solved?

**Comment by DG0lden** [comment]
I've tested it locally, it works now. Thanks

**Comment by borisskert** [comment]
I merged it.
